### PR TITLE
Improve logging output of function

### PR DESCRIPTION
**Pull request by Jaclynpqc**
This pull request enhances the logging output in the main.py file by strategically placing `logger.debug` statements in various functions. The improved logging provides detailed information about the execution flow, enabling easier debugging and troubleshooting.

I added logging statements relating to debug info, debug destination, file path directory, current version using: 
For example, 

```
Display verbose output? False
Debug level? DEBUG
Debug destination? SYSLOG
Current Chasten version 0.2.0
Using XPath version 2.0
```

I also add more logging statements at key points of the operation that likely going to cause error.
I attached a screenshot below, in which you could see two server CONSOLE and SYSLOG run at the same time for `chasten analyze`. While CONSOLE returns the checked patterns, SYSLOG returns some logging statement and info that might come in handy when troubleshooting and debugging the code: 
Screenshot 2023-11-21 at 3 02 12 PM

### CODE REVIEW

**Review by laurennevill — DISMISSED** [review]

**Review by gkapfham — CHANGES_REQUESTED** [review]
Hello @Jaclynpqc, can you please give examples of the output that this logging output would produce? Can you also confirm that you have tested it and shown that it works for all three of the major operating systems that we support? Also, can you please confirm that it works for both console logging and the syslog server?

**Comment by AlishChhetri** [comment]
This feature works on a linux device.

**Comment by Finley8** [comment]
This feature works on a Windows device!

**Comment by boulais01** [comment]
@Jaclynpqc Would you mind posting examples here of the elements @gkapfham requested, so we can close that request change?

**Review by gkapfham — DISMISSED** [review]
Hello @Jaclynpqc, thanks for this PR, it is helpful and now close to being merged. The main concern that I see right now is that the PR also includes an `analysis.md` file. This file was automatically created by the `chasten` program because it was running a feature that @Poiuy7312 created. Since this is a derived/generated file we want to make sure that we do not include it inside of our repository. Can you please remove this file and then request another review? Once you have made this change, I think that it should be ready for us to merge to the main trunk! Thanks!

**Review by AlishChhetri — APPROVED** [review]
Looks great! I have run the tool on my computer, Linux OS, and it does execute the desired result.

**Comment by laurennevill** [comment]
Once the changes are resolved, I can merge this

**Pull request merged**
