### PR TITLE
fix: removed interact command and trogon

### PR DESCRIPTION
**Pull request by Poiuy7312**
This removes the interact command entirely and the dependency trogon. It would crash anytime the analyze command was clicked on this seems to be a problem with trogon and not chasten itself

image_2023-09-29_093154940

This solves issue #79

Everything still works on Windows 11

### CODE REVIEW

**Comment by tuduun** [comment]
Great debugging, @Poiuy7312. Have you checked if Chasten works without the interact command and trogon on OS besides Windows 11? For example, MacOS and on Ubuntu?

**Review by gkapfham — APPROVED** [review]
Hello @Poiuy7312, thanks for removing this feature. I anticipate that we will have to remove this feature until the `trogon` dependency is more stable.

**Review by laurennevill — APPROVED** [review]
Nice work!

**Review by tuduun — APPROVED** [review]

**Comment by laurennevill** [comment]
Before merging, could you pull the recent changes made to main just to be safe.

**Pull request merged**
