### PR TITLE
feat: Workflow now checks more OS

### PR DESCRIPTION
**Pull request by Poiuy7312**
Previously the workflow only ran on Linux but now it should run on Linux, MacOS and Windows making it easier to make sure chasten is running properly on all major platforms.

### CODE REVIEW

**Comment by gkapfham** [comment]
Hello @Poiuy7312, is it possible for you to get this branch to a passing state for all of the different checks on all of the different operating systems that we support?

**Comment by gkapfham** [comment]
Hello @Poiuy7312, would this discussion help to solve the issue that you are facing?

https://github.com/Textualize/rich-cli/issues/67

**Comment by jnormile** [comment]
Adding @AidanNeeson as a reviewer; he'll be interested in the changes to CI/CD workflow.

**Review by AidanNeeson — DISMISSED** [review]
The new workflow looks great to me! Awesome job implementing the other two operating systems. This will surely help us moving forward.

**Review by laurennevill — DISMISSED** [review]

**Review by EvanNelson04 — APPROVED** [review]
This looks really good to me

**Review by laurennevill — APPROVED** [review]
This looks good. Thank you for your work, @Poiuy7312

**Review by boulais01 — APPROVED** [review]

**Pull request merged**
