### PR TITLE
fix: removed filelines from sources class in db.py

### PR DESCRIPTION
**Pull request by Poiuy7312**
This is a fix for issue #50 

The code still runs when removing the _filelines attribute:

Analyze:

image_2023-11-02_154601324

Integrate:

image_2023-11-02_154240473

Datasette-serve:

image_2023-11-02_154419880

### CODE REVIEW

**Comment by laurennevill** [comment]
Hey @gkapfham, this is priority 2.

**Review by laurennevill — DISMISSED** [review]
I think this looks good to merge. In the future, please try to have a description for your change when making your pull requests. Thanks for your work!

**Review by tuduun — COMMENTED** [review]
Have you done Professor Kapfhammer's recommendations for issue #50?

**Comment by gkapfham** [comment]
Hello @tuduun, I think that the solution in this case is to remove `filelines`, which is what this PR actually does. Can you confirm @Poiuy7312?

**Comment by Poiuy7312** [comment]
Yes it does just do that

**Review by gkapfham — CHANGES_REQUESTED** [review]
Hello @Poiuy7312, I agree that this fix is the right way forward. I also recognize that the change is very simple. With that said, the description of the PR does not currently provide enough evidence that this feature will not break other parts of the tool. Can you provide evidence that the `analyze` and `integrate` and `datasette-serve` commands are working correctly if we remove this from the full-text-search functionality?

**Comment by gkapfham** [comment]
@Poiuy7312 please note that I am not requested changes to the source code but rather to the PR itself. You can provide command-lines and/or screenshots to show the tool is still working after you have removed the variable from the list. Thanks!

**Review by laurennevill — APPROVED** [review]

**Review by AidanNeeson — APPROVED** [review]

**Comment by laurennevill** [comment]
Hey @Poiuy7312 , can you update this branch to master?

**Review by VitalJoseph — APPROVED** [review]
I can attest to this change not affecting the analyze, integrate, and datasette sub commands. I have manually changed the same source code in my own branch and successfully ran said commands. My team also has a pr that relates to this specific source code change and cannot progress until this changed has been pushed to the main branch.

**Pull request merged**
