### PR TITLE
WIP: Feature: Allow `min` and `max` values in any checks file to have `null` value

### PR DESCRIPTION
**Pull request by simojo**
This PR changes the json schema used in validation of checks files, and it changes the pydantic `BaseModel` class structure. See the diffs for details. This is one of two steps towards PR https://github.com/AstuteSource/chasten/issues/59. The next step after this is to change the local checks file: `.chasten/checks.yml`, which will be merged after this PR is merged.

### CODE REVIEW

**Comment by simojo** [comment]
It's worth noting that this also ships a fix where

* if `min` was null, then it would check if the number of checks is *higher* than `max`
* if `max` was null, then it would check if the number of checks is *lower* than `min`

This is, of course, the opposite of the expected behavior. See commit https://github.com/AstuteSource/chasten/pull/68/commits/682f54c46fe2751d1802b53851f54fa971e6524b for this fix.

**Review by jnormile — APPROVED** [review]
Directly related to PR #88 ; in any case, approved!

**Review by CalebKendra — APPROVED** [review]
This command is needed and works to fix the build

**Review by laurennevill — APPROVED** [review]
Looks good

**Pull request merged**
