### PR TITLE
Added Change to Typer call for help on no argument

### PR DESCRIPTION
**Pull request by CalebKendra**
made `chasten --help` command run when `chasten` is called.

I did this by changing the `typer` object creation to allow for `no_args_is_help=True`

### CODE REVIEW

**Comment by CalebKendra** [comment]
@gkapfham I don't know the TL's Github handles, could you link them so they see this pull request?

**Comment by CalebKendra** [comment]
@laurennevill Plz merge plz

**Review by laurennevill — APPROVED** [review]
This looks good to me. I believe you'd still need comment from @gkapfham before we can officially merge.

**Review by jnormile — APPROVED** [review]
Clean and straightforward fix. Thumbs-up from me!

Props on digging up the `no_args_is_help` parameter for `Typer` objects. Good investigative work!

**Review by gkapfham — APPROVED** [review]
I approve these changes. Thanks for making this PR @CalebKendra.

**Pull request merged**
