### PR TITLE
Change --Xpath Versions While Using Chasten Analyze

### PR DESCRIPTION
**Pull request by VitalJoseph**
When creating a pull request to add a new feature or alter an existing one,
there are some important elements to include to help our team review and process it more efficiently.

1. Make sure the title is descriptive of what the PR includes. Don't mention issue names/numbers; save that for the description.

2. List the names of those who contributed to the project.

Vital Joseph, Finley Banas, Keven Duverglas, Jason 

3. Link the issue the pull request is meant to fix/resolve.

https://github.com/AstuteSource/chasten/tree/issue-%2315

4. Describe the contents and goal of the pull request.

The contents of this pull request consists of changes to the command line interface for the analyze function in chasten as well as code that allows the user to specify which xpath parser is ran while parsing the the xpath patterns in the checks.yml file.

5. Will coverge be maintained/increased? 

The coverage that is maintained/increased has to do with the speed of chasten analyze. Using different versions of xpath we can run the analyze command faster based on what program the user is analyzing.

6. What operating systems has this been tested on? How were these tests conducted?

Mac and Windows

7. Include a code block and/or screenshots displaying the functionality of your feature, if applicable/possible.

poetry run chasten analyze multicounter --config /Users/finle/chasten/astute_subjects/chasten-configuration -xp 1.0 --search-path /Users/finle/chasten/astute_subjects/subject_forks/multicounter/ --save-directory /Users/finle/chasten/astute_subjects/subject_forks/multicounter --debug-level ERROR --debug-dest SYSLOG --save

image

poetry run chasten analyze multicounter --config /Users/finle/chasten/astute_subjects/chasten-configuration -xp 2.0 --search-path /Users/finle/chasten/astute_subjects/subject_forks/multicounter/ --save-directory /Users/finle/chasten/astute_subjects/subject_forks/multicounter --debug-level ERROR --debug-dest SYSLOG --save

image

Mark as a draft until it is ready to begin the reviewing process, then tag our [Lead Software Architect, Lauren Nevill](https://github.com/laurennevill),
our [Principal Software Engineer, Bergas Batara](https://github.com/bergasanargya), and our [Founding Engineer, Gregory Kapfhammer](https://github.com/gkapfham)
when you mark it as ready for review.

### CODE REVIEW

**Comment by Finley8** [comment]
@laurennevill @bergasanargya @gkapfham

**Comment by laurennevill** [comment]
@gkapfham, if your work fixes the build issues in this PR, then this would be priority 3

**Comment by KevenDuverglas** [comment]
This is a great enhancement that will allow for the improved speed of Chasten. And will allow Chasten to have more variety in its
usage.

**Comment by bergasanargya** [comment]
Can you explain further your feature here @VitalJoseph @Finley8? How can this feature be helpful on the speed running the chasten software? What implementation do you have that could help chasten?

**Review by KevenDuverglas — APPROVED** [review]
I think this would be a great addition to chasten.

**Comment by gkapfham** [comment]
Hello @VitalJoseph can you please @-mention the specific people who were the main collaborators for this feature in your description of the PR?

**Comment by gkapfham** [comment]
Hello @Finley8 and @VitalJoseph can you please answer the questions that @bergasanargya raised?

**Comment by Finley8** [comment]
Hello @bergasanargya, thanks for the question. The new implementation will help speed up the chasten analyze command while analyzing multiple programs. The user can also determine whether XPath 1 or XPath 2 analyzes their program quicker by looking at the timer module that is returned after a check.

**Review by Finley8 — APPROVED** [review]

**Review by laurennevill — APPROVED** [review]

**Review by AidanNeeson — APPROVED** [review]

**Pull request merged**
