### PR TITLE
Adding the Policies, Documentation, and Templates to Improve Community Standards

### PR DESCRIPTION
**Pull request by boulais01**
Progress made to complete Issue #3 (The addition of files to improve our community policies)

### CODE REVIEW

**Comment by boulais01** [comment]
@laurennevill Good points. Fixed.

**Review by laurennevill — DISMISSED** [review]
This looks good to me. Great work, everyone

**Comment by gkapfham** [comment]
Hello @boulais01 can you please rename this PR so that it has a descriptive title?

**Comment by gkapfham** [comment]
Hello @boulais01 is this PR making "progress" or does it resolve the referenced issue?

**Comment by boulais01** [comment]
@gkapfham The current state of the PR is the resolution of Issue #3. I have adjusted the title to reflect this.

**Comment by boulais01** [comment]
@gkapfham Title updated

**Comment by hayleepierce** [comment]
@bergasanargya Please take the time to review this. Thanks!

**Comment by bergasanargya** [comment]
Looks good to me on adding the policies, documentation and templates. It just has to be sure that everyone could find all these documentation easily so everyone are able to follow all the guidelines.

**Review by bergasanargya — APPROVED** [review]

**Review by laurennevill — APPROVED** [review]

**Comment by gkapfham** [comment]
> Looks good to me on adding the policies, documentation and templates. It just has to be sure that everyone could find all these documentations easily so everyone are able to follow all the guidelines.

Hi @bergasanargya you need to complete a formal review of the PR.

**Comment by laurennevill** [comment]
@bergasanargya have you had some time to review this PR? It would be beneficial to have some of these templates up and running for future PRs.

**Review by jnormile — APPROVED** [review]
Verbose community standards that clearly articulate expectations for contributing to the project. Well done!

**Review by AlishChhetri — APPROVED** [review]
This looks great! I will work on adding this content to the external site this week.

**Pull request merged**
