### PR TITLE
Display Counts of files in each directory when running Chasten Integrate.

### PR DESCRIPTION
**Pull request by VitalJoseph**
When creating a pull request to add a new feature or alter an existing one,
there are some important elements to include to help our team review and process it more efficiently.

1. Make sure the title is descriptive of what the PR includes. Don't mention issue names/numbers; save that for the description.

2. List the names of those who contributed to the project.

@VitalJoseph  @KellerLiptrap 

3. Link the issue the pull request is meant to fix/resolve.

https://github.com/AstuteSource/chasten/issues/5

4. Describe the contents and goal of the pull request.

The goal of this pull request is to display counts of processed data in each directory when running the chasten integrate sub-command. As well as provide the total count of processed data.

5. Will coverge be maintained/increased? 

Coverage should be maintained.

6. What operating systems has this been tested on? How were these tests conducted?

macos, these tests were conducted in a poetry shell.

7. Include a code block and/or screenshots displaying the functionality of your feature, if applicable/possible.

```python
poetry run chasten integrate --save-directory /Users/vj2/cmpsc203/chasten/astute_subjects/subject_data/integrated-data all-programs 
/Users/vj2/cmpsc203/chasten/astute_subjects/subject_data/multicounter/chasten-results-multicounter-20231017153319-cb184165beba4f54807006fec9dba51a.json 
/Users/vj2/cmpsc203/chasten/astute_subjects/subject_data/lazytracker/chasten-results-lazytracker-20231017160805-d6e71b9fb32a4c71a2712ccdcf8ebff7.json
```
Screenshot 2023-11-03 at 9 37 07 AM

Mark as a draft until it is ready to begin the reviewing process, then tag our [Lead Software Architect, Lauren Nevill](https://github.com/laurennevill),
our [Principal Software Engineer, Bergas Batara](https://github.com/bergasanargya), and our [Founding Engineer, Gregory Kapfhammer](https://github.com/gkapfham)
when you mark it as ready for review.

### CODE REVIEW

**Comment by bergasanargya** [comment]
Hi @VitalJoseph, has this feature been tested in any other OS systems; Windows or Linux? Also how can this feature can be useful for the chasten software?

**Comment by VitalJoseph** [comment]
> Hi @VitalJoseph, has this feature been tested in any other OS systems; Windows or Linux? Also how can this feature can be useful for the chasten software?

No this has only been tested on macos but passes the builds for other os systems. This feature will enhance the chasten integrate sub command by adding the counts of processed data in each directory as well as in total.

**Review by gkapfham — DISMISSED** [review]
Hello @VitalJoseph, can you please test this feature on all of the major operating systems that we support and confirm that it works correctly as @bergasanargya has requested? Thanks!

**Comment by VitalJoseph** [comment]
hey @Finley8 @KevenDuverglas can you please test our feature in our branch named "issue-#5". Examples are provided above.

**Comment by Finley8** [comment]
I attempted to test your project. I was unable to generate a `.json` file using `chasten analyze`. I will attempt to fix this and try again.

**Comment by boulais01** [comment]
@VitalJoseph @KellerLiptrap @Finley8 As you work on adjusting this to work on other OSs, please consider reviewing the proper commit message format and ensuring that if it is still being worked on, it is marked as draft or WIP. If not, please share in the Discord to help get tests from those with other OSs.

**Comment by VitalJoseph** [comment]
hey @MilesF25 whenever you get a chance could you test run our feature in our remote branch (issue-#5)

**Comment by MilesF25** [comment]
@VitalJoseph Just to be clear the chasten configuration repo I need to run is the one in AstuteSorce?

**Comment by VitalJoseph** [comment]
> @VitalJoseph Just to be clear the chasten configuration repo I need to run is the one in AstuteSorce?

yes @MilesF25 you can use this command as a template for windows 

```poetry run chasten analyze multicounter --config /Users/finle/chasten/astute_subjects/chasten-configuration -xp 2.0 --search-path /Users/finle/chasten/astute_subjects/subject_forks/multicounter/ --save-directory /Users/finle/chasten/astute_subjects/subject_data/multicounter --debug-level ERROR --debug-dest SYSLOG --save```

You also need to make a folder called subject_data where you just have an empty folder for multicounter and lazytracker, that’s where you json file should end up after running analyze.

And then the ones you git clone (subject_forks) are the ones you would use for the —search-path argument.

**Comment by MilesF25** [comment]
I was able to run it successfully.

**Review by MilesF25 — APPROVED** [review]
I was able to run it.

**Comment by boulais01** [comment]
@VitalJoseph does Miles' test means all OSs have been covered? If so, feel free to resolve the change request, and we'll work on making sure this gets the necessary reviews.

**Review by laurennevill — APPROVED** [review]

**Review by tuduun — APPROVED** [review]
Great work on the OS confirmation!

**Pull request merged**
