### PR TITLE
feat: give analyze the ability to display browsable results

### LINKED ISSUE #30: Create a Markdown Report (Or Some Other "Browse-able" Report) for an Analysis
While `chasten analyze` provides a significant amount of output, especially when it is run in verbose mode, it does not have a way to save an analysis report in any format except for JSON. It would be nice if the tool could also produce a "browse-able" report in Markdown format or, alternatively, offer a terminal user-interface (TUI) mode that supports the browsing of results. Ultimately, the tool needs some human-friendly way to browse the results! With that said, it is important to note that there _is_ one way to browse results right now --- and that is through the Datasette interface that you can run after using the `chasten integrate` and `chasten datasette-serve` or `chasten datasette-publish` commands. However, these seem somewhat "heavyweight" and I anticipate that it will still be great if there was a way to browse one or more result files in a terminal window either by using `rich-cli` on a Markdown file or through a bespoke TUI.

### PR DESCRIPTION
**Pull request by Poiuy7312**
closes #30 

This gives analyze the sub commands --markdown-storage/-r and --display for storing the results in a markdown file and displaying it as a browsable frogmouth display when using --display

Ex 

`chasten analyze chasten --config $PWD/.chasten/ --debug-level ERROR --debug-dest CONSOLE --search-path . -r . --display`

```text
💫 chasten: Analyze the AST of Python Source Code
🔗 GitHub: https://github.com/gkapfham/chasten

✨ Configuration directory: C:\Users\Preston\CMPSC-203\ChastenProject\chasten\.chasten

✨ Validated C:\Users\Preston\CMPSC-203\ChastenProject\chasten\.chasten/config.yml? Yes
✨ Validated C:\Users\Preston\CMPSC-203\ChastenProject\chasten\.chasten/checks.yml? Yes

🐸 Frogmouth Information

 • Venv: C:\Users\Preston\AppData\Local\pypoetry\Cache\virtualenvs\chasten-Ti8Qy4ta-py3.11
 • Program: C:\Users\Preston\AppData\Local\pypoetry\Cache\virtualenvs\chasten-Ti8Qy4ta-py3.11/Scripts/frogmouth.exe
```

Display example:

image_2023-10-31_152614171

### CODE REVIEW

**Comment by Poiuy7312** [comment]
I'm not sure if this is what was wanted but this is my attempt of giving something that stores the results in a readable form

**Review by tuduun — COMMENTED** [review]
Hey @Poiuy7312 , can you please be more descriptive on what changes you have made on this PR? It would be helpful for your team if you could provide a description of what you have made that closes the issue #30 .

**Comment by gkapfham** [comment]
Hi @Poiuy7312 can you give an example of what the command-line looks like?
Can you also please give a screenshot that shows what output this produces?

**Comment by gkapfham** [comment]
Thanks @Poiuy7312 this is an awesome feature!

**Review by gkapfham — APPROVED** [review]

**Comment by gkapfham** [comment]
Hello @Poiuy7312 can you confirm that this is only for the `analyze` sub-command?

**Comment by gkapfham** [comment]
Also @tuduun, @laurennevill, and/or @jnormile can you review this and provide feedback?

**Comment by Poiuy7312** [comment]
Yes this is only for analyze

**Review by laurennevill — DISMISSED** [review]
I think this looks good. Thank you for including a descriptive PR with screenshots and examples. Great work!

**Review by boulais01 — COMMENTED** [review]
One really nitpicky thing - I would say that in main.py, on line 390, I would order the error codes to ignore numerically, so it goes `# noq: PLR0912, PLR0913, PLR0915`.

**Comment by boulais01** [comment]
Something I just noticed as well - make sure you update to master as well

**Comment by simojo** [comment]
Just as a note, merging master into your branch still hasn't fixed the downgrading of `poetry.lock`.

**Comment by boulais01** [comment]
@Poiuy7312 I was going to try and resolve the conflicts between the master main.py and the main.py here, but I'm not sure what some of the resolutions should be to maintain functionality. It's only three conflicts, so it shouldn't take long to resolve when you get the chance.

**Review by laurennevill — APPROVED** [review]

**Review by KevenDuverglas — APPROVED** [review]

**Pull request merged**
