### PR TITLE
Fix: local checkfile used in testing is now general enough

### PR DESCRIPTION
**Pull request by simojo**
Previously, the local checkfile `.chasten/checks.yml` had checks searching for things like doubly-nested `if` statements found in the `chasten` source code. Because finding things like this in our repository source code is not set in stone, I have changed this to be general enough to effectively test the functionality without making false assumptions such as the one previously mentioned.

Closes https://github.com/AstuteSource/chasten/issues/59

**NOTE:** depends on #68 before merging.

**NOTE:** @gkapfham is pointing out that #68 has now been merged.

### CODE REVIEW

**Comment by simojo** [comment]
It appears that we're having problems with coverage here. I'll continue to look into this and comment what I find here. I was not expecting this. @laurennevill

**Comment by laurennevill** [comment]
Hey @gkapfham, this is priority one for merges

**Comment by simojo** [comment]
The problem with coverage is still unidentified and unsolved, just letting this thread know.

**Review by boulais01 — APPROVED** [review]

**Comment by simojo** [comment]
@laurennevill @gkapfham , Mordred and I found that the failing checks is a transient issue. I suspect that, because coverage is time consuming, the process is timing out, but this does not appear to be obvious anywhere. Regardless, we have proven that the issue is not consistent, and we both recommend merging this when possible.

**Pull request merged**
