### PR TITLE
Feature: adds version command to `chasten`

### PR DESCRIPTION
**Pull request by CalebKendra**
This adds a command to be able to check the version of `chasten` via PyPi. `chasten version` runs:

```txt
chasten 0.1.1
```

### CODE REVIEW

**Comment by CalebKendra** [comment]
The `files changed` tab is messed up due to the resetting of branches on this branch, in order to fully review this change make sure to look at the `version` function in `main.py` and the `get_chasten_version` function in `util.py`.

**Comment by laurennevill** [comment]
It looks like this PR does not have a passing build. Please look into this and I will be happy to review once the build is passing. Thanks!

**Review by laurennevill — APPROVED** [review]
This looks really good. Great work everyone!

**Review by hayleepierce — APPROVED** [review]

**Review by jnormile — APPROVED** [review]
Straightforward fix to a straightforward problem. Thanks for implementing!

**Pull request merged**
