### PR TITLE
fix: Datasette-serve command not running correctly on Windows

### PR DESCRIPTION
**Pull request by Poiuy7312**
This adds a function in util.py called get_OS() which gets what the OS of the user so MacOS, Linux or Windows. This was implemented because there was an issue with the Datasette-serve command on windows would look in the wrong directory for the executable for datasette. So I changed to look in a different directory Scripts if its run on Windows and then it looks for them in the Bin file when run on anything else 

I also added a function in database.py which creates a path to the executable which the function Datasette-serve previously did itself. This was done because it made it a lot easier to make sure that the added feature works as intended and allowed me to write a test case for it.

### CODE REVIEW

**Comment by gkapfham** [comment]
Hello @Poiuy7312, please note that you need to use the commit standard that we have adopted for this project: https://www.conventionalcommits.org/en/v1.0.0/.

**Comment by gkapfham** [comment]
Hello @Poiuy7312 your description of this PR needs to clearly explain what this will change in the main codebase and in the main tool once it is merged. Can you please furnish an example of what did _not_ work before you made the changes and then what now _does_ work if we merge this PR? You are also welcome to reference an issue in the issue tracker when you explain your PR.

**Review by laurennevill — COMMENTED** [review]
It looks like you've successfully identified and remedied a bug in Chasten and I think this looks good.

I see this code also has a test which would be @tuduun's area of expertise. I'd like to see his review specifically on this PR before approving and merging. Thanks for your work!

**Comment by gkapfham** [comment]
Hello @Poiuy7312 is this PR fully updated so that it contains the new build matrix setup for running everything in GitHub Actions?

**Review by tuduun — APPROVED** [review]
Great work on configuring the path for all macOS, windows, and Ubuntu. You even tested the code! I will grant the merge request, and I would encourage prof @gkapfham to take a final look at this before anyone merges it!

**Comment by Poiuy7312** [comment]
> Hello @Poiuy7312 is this PR fully updated so that it contains the new build matrix setup for running everything in GitHub Actions?

Yes

**Review by laurennevill — APPROVED** [review]
This looks good.

**Comment by boulais01** [comment]
Hey @tuduun @gkapfham @jnormile would one of you mind giving this a look?

**Review by boulais01 — APPROVED** [review]

**Comment by boulais01** [comment]
@tuduun We are still waiting on your review, when you get the chance.

**Review by jnormile — APPROVED** [review]
An important fix! Passing build, some additional testing to support new code--looks like a winner to me! (Sorry the review took so long!)

**Pull request merged**
