### PR TITLE
Adding A Comparisons Section to README 

### PR DESCRIPTION
**Pull request by EvanNelson04**
This pull request is based on issue #9 - compare chasten to tools like symbex

What we have done is added a section in the readme called "Comparisons". What this section does is compare our chasten tool to other similar tools, specifically symbex. We would love reviews on the content and on the formatting before we go ahead and merge.

### CODE REVIEW

**Comment by boulais01** [comment]
@EvanNelson04 Is this complete and ready for review?

**Comment by boulais01** [comment]
@EvanNelson04 Please note if this is complete or not. Also, please note our template for creating PRs - the issue does notneed to be in the title. I recommend also looking at the correct commit message formatting.

**Comment by EvanNelson04** [comment]
> @EvanNelson04 Please note if this is complete or not. Also, please note our template for creating PRs - the issue does not need to be in the title. I recommend also looking at the correct commit message formatting.

**Comment by EvanNelson04** [comment]
> @EvanNelson04 Please note if this is complete or not. Also, please note our template for creating PRs - the issue does not need to be in the title. I recommend also looking at the correct commit message formatting.

I need to make a few final edits for this so it is not finished yet

**Comment by gkapfham** [comment]
Hello @EvanNelson04, are you now finished with this PR? We need to finish these updates to the documentation as soon as is possible. Thanks!

**Comment by boulais01** [comment]
@EvanNelson04 Please either finish this or ensure someone can take over for you.

**Comment by boulais01** [comment]
@Jaclynpqc would you consider taking this work on as part of documentation? @EvanNelson04 If so, can you give Jaclyn contributor access to your code?

**Pull request closed without merging**
